# Generated by Django 3.0.6 on 2020-06-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=20)),
                ('cash_buy', models.DecimalField(decimal_places=7, max_digits=15)),
                ('cash_sell', models.DecimalField(decimal_places=7, max_digits=15)),
                ('spot_buy', models.DecimalField(decimal_places=7, max_digits=15)),
                ('spot_sell', models.DecimalField(decimal_places=7, max_digits=15)),
            ],
        ),
    ]
