# Generated by Django 3.0.6 on 2020-06-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exrate',
            name='cash_buy',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='exrate',
            name='cash_sell',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='exrate',
            name='spot_buy',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='exrate',
            name='spot_sell',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
