# Generated by Django 3.0.6 on 2020-06-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200609_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExrateQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=20)),
                ('cash_buy', models.DecimalField(decimal_places=5, max_digits=15)),
                ('cash_sell', models.DecimalField(decimal_places=5, max_digits=15)),
                ('spot_buy', models.DecimalField(decimal_places=5, max_digits=15)),
                ('spot_sell', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
        ),
    ]
