# Generated by Django 3.0.6 on 2020-06-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_exratequery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exrate',
        ),
        migrations.DeleteModel(
            name='ExrateQuery',
        ),
    ]
