# Generated by Django 3.0.7 on 2020-06-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_exratequery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcoExrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=2)),
                ('day_r', models.IntegerField()),
                ('currency', models.CharField(max_length=20)),
                ('bco_buy', models.DecimalField(decimal_places=5, max_digits=15)),
                ('bco_sell', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
        ),
    ]
