# Generated by Django 3.0.7 on 2021-05-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_tiptopuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_date', models.DateField()),
                ('cpf01', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=1)),
                ('status1', models.TextField()),
                ('status2', models.CharField(max_length=1)),
            ],
        ),
    ]
