# Generated by Django 3.0.7 on 2021-05-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_health_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='status0',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
